[project]
name = "scuffle-src"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "nuitka>=2.6.9",
]
